
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author nancy
 */
public class Adstud extends javax.swing.JFrame {

    /**
     * Creates new form Adstud
     */
    public Adstud() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        astudid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        astudname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        astuddeg = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        astudage = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        astudemail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(525, 225));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("ADD NEW STUDENT ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 370, 40));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText(" STUDENT ID       :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 270, -1));

        astudid.setBackground(new java.awt.Color(255, 255, 204));
        astudid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                astudidActionPerformed(evt);
            }
        });
        getContentPane().add(astudid, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 290, 30));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("STUDENT NAME:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 210, 30));

        astudname.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(astudname, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 290, 30));

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setText("DEGREE               :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 190, 30));

        astuddeg.setBackground(new java.awt.Color(255, 255, 204));
        astuddeg.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        astuddeg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT YOUR DEGREE", "IT", "CSE", "AIDS", "EEE", "ECE", "MECH", " ", " " }));
        astuddeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                astuddegActionPerformed(evt);
            }
        });
        getContentPane().add(astuddeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 290, 30));

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setText("AGE                     :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 190, -1));

        astudage.setBackground(new java.awt.Color(255, 255, 204));
        astudage.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        getContentPane().add(astudage, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 290, 30));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 255));
        jLabel6.setText("EMAIL                 :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 200, -1));

        astudemail.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(astudemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 290, 30));

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 110, 30));

        jButton2.setBackground(new java.awt.Color(255, 255, 204));
        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jButton2.setText("CLOSE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 110, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\nancy\\Music\\IMG_20230513_214906.jpg")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void astuddegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_astuddegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_astuddegActionPerformed

    private void astudidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_astudidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_astudidActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         
         String id1= astudid.getText();
         String name1=astudname.getText();
         String deg=astuddeg.getName();
         String age=astudage.getText();
         String mail=astudemail.getText();
        //int rno = Integer.parseInt(ID);
       
        try {
          Class.forName("com.mysql.jdbc.Driver");
    try(Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/jdbcexam","root","samyu_park")) {
        Statement stm = conn.createStatement();
        String sql = "insert into adstud values('"+id1+"','"+name1+"','"+deg+"','"+age+"','"+mail+"')";
        stm.executeUpdate(sql);
        String sql1 = "insert into login1 values('"+id1+"','"+name1+"')";
        stm.executeUpdate(sql1);
        String sql2 = "insert into stud values('"+id1+"','"+name1+"','"+deg+"','"+age+"','"+mail+"')"; 
        stm.executeUpdate(sql1);
        javax.swing.JOptionPane.showMessageDialog(this,"Inserted");
    }
         
           
        }catch(HeadlessException | ClassNotFoundException | SQLException e)
        {
           
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
dispose();
        //new Adhome().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adstud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adstud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adstud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adstud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adstud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField astudage;
    private javax.swing.JComboBox<String> astuddeg;
    private javax.swing.JTextField astudemail;
    private javax.swing.JTextField astudid;
    private javax.swing.JTextField astudname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
