
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author nancy
 */
public class Update extends javax.swing.JFrame {

    /**
     * Creates new form Update
     */
    public Update() {
         data_load();
        initComponents();
        
    }
     public void data_load()
    {
        try{
            Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/jdbcexam","root","samyu_park");
            java.sql.Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery("select * from nb");
            Vector v=new Vector();
            while(rs.next())
            {
                v.add(rs.getString("bid"));
                DefaultComboBoxModel com=new DefaultComboBoxModel(v);
                jTable1.setModel((TableModel) com);


            }

        }catch(Exception e)
        {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bt = new javax.swing.JTextField();
        isbn1 = new javax.swing.JTextField();
        bid = new javax.swing.JTextField();
        w = new javax.swing.JTextField();
        c = new javax.swing.JTextField();
        pr = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 255));
        jLabel1.setText("BOOK TITLE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 150, 30));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("ISBN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 255));
        jLabel3.setText("BOOK ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 255, 255));
        jLabel4.setText("WRITER");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 255, 255));
        jLabel5.setText("CATEGORY");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 160, 30));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 255, 255));
        jLabel6.setText("PRICE");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActionPerformed(evt);
            }
        });
        getContentPane().add(bt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 140, -1));
        getContentPane().add(isbn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 140, -1));
        getContentPane().add(bid, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 140, -1));
        getContentPane().add(w, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 140, -1));
        getContentPane().add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 140, -1));
        getContentPane().add(pr, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 140, -1));

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 255, 255));
        jLabel7.setText("UPDATE");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "bt", "isbn1", "bid", "w", "c", "pr"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 510, -1));

        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, -1, -1));

        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, -1, -1));

        jButton3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jButton3.setText("ADD");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\nancy\\Music\\l5.jpg")); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1680, 830));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if(bt.getText().isEmpty()||isbn1.getText().isEmpty()||bid.getText().isEmpty()||w.getText().isEmpty()||c.getText().isEmpty()||pr.getText().isEmpty()) 
{
     JOptionPane.showMessageDialog(this, "MISSING");
}// TODO add your handling code here:
else
{
try{
    String bt1=bt.getText();
    String isbn2=isbn1.getText();
    String bid1=bid.getText();
    String w1=w.getText();
    String c1=c.getText();
    String pr1=pr.getText();
    Class.forName("com.mysql.jdbc.Driver");
          Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/jdbcexam","root","samyu_park");
          java.sql.Statement stmt = conn.createStatement();
                      String s="update nb set bt='"+bt1+"',isbn1='"+isbn2+"',bid='"+bid1+"',w='"+w1+"',c='"+c1+"',pr='"+pr1+"' where bid='"+bid1+"'";

             System.out.println(s);
              int n=stmt.executeUpdate(s);
              System.out.println(n+"rows");
        stmt.close();
        conn.close();
     //   JOptionPane.showMessageDialog(null,"SUCCESFULLY SAVED");
JOptionPane.showMessageDialog(null,"SUCCESFULLY MODIFIED");
DefaultTableModel tblmodel=(DefaultTableModel)jTable1.getModel();
             if(jTable1.getSelectedRowCount()==1){
                 tblmodel.setValueAt(bt1, jTable1.getSelectedRow(), 0);
                 tblmodel.setValueAt(isbn2, jTable1.getSelectedRow(), 1);
                 tblmodel.setValueAt(bid1, jTable1.getSelectedRow(), 2);
                 tblmodel.setValueAt(w1, jTable1.getSelectedRow(), 3);
                   tblmodel.setValueAt(c1, jTable1.getSelectedRow(), 4);
 tblmodel.setValueAt(pr1, jTable1.getSelectedRow(), 4);


}
             
}
catch(ClassNotFoundException|SQLException ex)
{

}
}

    
      /* PreparedStatement pst = conn.prepareStatement(s);
       pst.execute();
       JOptionPane.showMessageDialog(null,"Updated");
}
catch(Exception e)
{
JOptionPane.showMessageDialog(null,e);
}*/
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
new Adhome().setVisible(true);
                        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
if(bt.getText().equals("")||isbn1.getText().equals("")||bid.getText().equals("")||w.getText().equals("")||c.getText().equals("")||pr.getText().equals("")) 
{
     JOptionPane.showMessageDialog(this, "PLEASE ENTER ALL FIELDS");
}// TODO add your handling code here:
else{
            String data[]={bt.getText(),isbn1.getText(),bid.getText(),w.getText(),c.getText(),pr.getText(),};
            DefaultTableModel tblmodel=(DefaultTableModel)jTable1.getModel();
            tblmodel.addRow(data);


        }
try{
    
              
    String bt1=bt.getText();
    String isbn2=isbn1.getText();
    String bid1=bid.getText();
    String w1=w.getText();
    String c1=c.getText();
    String pr1=pr.getText();
    Class.forName("com.mysql.jdbc.Driver");
          Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/jdbcexam","root","samyu_park");
          java.sql.Statement stmt = conn.createStatement();
                      String s="insert into nb values('"+bt1+"','"+isbn2+"','"+bid1+"','"+w1+"','"+c1+"','"+pr1+"')";

             System.out.println(s);
              int n=stmt.executeUpdate(s);
              System.out.println(n+"rows");
        stmt.close();
        conn.close();
        JOptionPane.showMessageDialog(null,"SUCCESFULLY SAVED");


}
catch(ClassNotFoundException|SQLException ex)
{

}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      DefaultTableModel tblmodel=(DefaultTableModel)jTable1.getModel();
      int Myindex=jTable1.getSelectedRow();
    bt.setText(tblmodel.getValueAt(Myindex, 0).toString());
isbn1.setText(tblmodel.getValueAt(Myindex, 1).toString());
bid.setText(tblmodel.getValueAt(Myindex, 2).toString());
w.setText(tblmodel.getValueAt(Myindex, 3).toString()); 
c.setText(tblmodel.getValueAt(Myindex, 4).toString());
pr.setText(tblmodel.getValueAt(Myindex, 5).toString());
// TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bid;
    private javax.swing.JTextField bt;
    private javax.swing.JTextField c;
    private javax.swing.JTextField isbn1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField pr;
    private javax.swing.JTextField w;
    // End of variables declaration//GEN-END:variables

}
